export const ADD_PRODUCT_TO_CART = 'ADD_PRODUCT_TO_CART';
export const REMOVE_PRODUCT_FROM_CART = 'REMOVE_PRODUCT_FROM_CART';
export const COMPLETE_CHECKOUT = 'COMPLETE_CHECKOUT';
export const SHOW_CART_MODAL = 'SHOW_CART_MODAL';

